'use strict';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const KEY='safety-basis-v1';let data=structuredClone(window.SEED),selected=data[0].id,admin=false,editing=null,lastDeleted=null;
function toast(s){$('#toast').textContent=s;$('#toast').classList.add('show');clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>$('#toast').classList.remove('show'),3500)}
function validate(arr){if(!Array.isArray(arr)||arr.length>3000)throw Error('应为不超过3000条的隐患数组');const ids=new Set();for(const r of arr){for(const k of ['id','title','category','keywords','description','measures','note','mode','status','checked'])if(typeof r[k]!=='string'||r[k].length>30000)throw Error('条目字段缺失或格式错误：'+k);if(!r.id||!r.title||ids.has(r.id))throw Error('ID重复或名称为空');ids.add(r.id);if(!Array.isArray(r.places)||!r.places.length||r.places.some(x=>typeof x!=='string'))throw Error('场所类型无效');if(!['待核验','已核验','已失效'].includes(r.status))throw Error('核验状态无效');if(!['条件适用','直接适用','上位法兜底'].includes(r.mode))throw Error('匹配类型无效');if(!Array.isArray(r.bases)||!r.bases.length||r.bases.length>30)throw Error('每条需1至30条依据');for(const b of r.bases){for(const k of ['name','article','quote','url','level','scope','role'])if(typeof b[k]!=='string'||b[k].length>30000)throw Error('法规字段无效：'+k);if(b.url&&!/^https?:\/\//i.test(b.url))throw Error('来源链接必须使用http或https');}if(r.status==='已核验'&&(!/^\d{4}-\d{2}-\d{2}$/.test(r.checked)||r.bases.some(b=>!b.quote.trim()||!b.url.trim())))throw Error('已核验条目必须包含核验日期、原文和来源链接');}return arr}
try{const raw=localStorage.getItem(KEY);if(raw)data=validate(JSON.parse(raw));}catch(e){setTimeout(()=>toast('本地数据无法读取，已显示初始库；原始数据未覆盖'),100)}
function save(next){try{validate(next);localStorage.setItem(KEY,JSON.stringify(next));data=next;return true}catch(e){toast('未保存：'+e.message);return false}}
function places(){const old=$('#place').value;$('#place').innerHTML='<option value="">全部场所</option>'+[...new Set(data.flatMap(r=>r.places))].sort().map(v=>`<option>${esc(v)}</option>`).join('');$('#place').value=old;}
function matchBasis(b){const l=$('#level').value,r=$('#region').value;return(!l||b.level===l)&&(!r||b.scope.includes(r))}
function filtered(){const terms=$('#search').value.trim().toLowerCase().split(/\s+/).filter(Boolean),p=$('#place').value;return data.filter(r=>(admin||r.status!=='已失效')&&(!p||r.places.includes(p))&&r.bases.some(matchBasis)&&terms.every(t=>[r.title,r.keywords,r.description,r.category,...r.places,...r.bases.map(b=>b.name+' '+b.article)].join(' ').toLowerCase().includes(t)));}
function pill(r){return `<span class="pill ${r.status==='已失效'?'red':r.mode!=='直接适用'||r.status==='待核验'?'amber':''}">${esc(r.status==='已核验'?r.mode:r.status)}</span>`}
function render(){const rows=filtered();if(!rows.some(r=>r.id===selected))selected=rows[0]?.id;$('#count').textContent=rows.length;$('#summary').textContent=admin?'管理模式 · 编辑、备份与新增':'选择条目查看完整依据';$('#list').innerHTML=rows.length?rows.map(r=>`<button class="card ${r.id===selected?'selected':''}" data-id="${esc(r.id)}" aria-pressed="${r.id===selected}"><div class="meta"><span>${esc(r.id)} <span style="margin-left:8px">${esc(r.category)}</span></span>${pill(r)}</div><h3>${esc(r.title)}</h3><p>${esc(r.places.join(' / '))}</p><span class="arrow">↗</span></button>`).join(''):'<div class="empty"><strong>暂未找到匹配隐患</strong><br>试试缩短关键词，或重置场所和法规筛选。<br>也可以在隐患库管理中新增。</div>';$$('.card').forEach(el=>el.onclick=()=>{selected=el.dataset.id;render()});detail();}
function detail(){const r=data.find(x=>x.id===selected);if(!r){$('#detail').innerHTML='<div class="empty"><strong>让每条依据都适用</strong><br>选择一个隐患，查看专业描述、法规原文和整改措施。</div>';return}const bases=r.bases.filter(matchBasis);$('#detail').innerHTML=`<div class="detailtop"><div class="topline"><span class="eyebrow">${esc(r.id)} / ${esc(r.category)}</span>${pill(r)}</div><h2>${esc(r.title)}</h2><div class="subtitle">${esc(r.places.join(' · '))}<br>${r.status==='已核验'?'原文已核对':'核验状态：'+esc(r.status)} · ${esc(r.checked||'未填写日期')} · 使用前复核现行有效性</div></div><div class="detailbody"><section class="block"><h3><span class="number">01</span>隐患专业描述</h3><p>${esc(r.description)}</p></section><section class="block"><h3><span class="number">02</span>法规原文依据 <small style="font-weight:400;color:#98a08f">${bases.length} 条${bases.length!==r.bases.length?' · 已按筛选显示':''}</small></h3>${bases.map(b=>`<div class="basis"><div class="basismeta"><span class="pill ${b.role.includes('兜底')?'amber':''}">${esc(b.role)}</span><span class="article">${esc(b.level)} · ${esc(b.scope)}</span></div><h4>${esc(b.name)}</h4><span class="article">${esc(b.article)}</span><blockquote>${esc(b.quote||'尚未录入原文，请核验后补充。')}</blockquote>${b.url?`<a href="${esc(b.url)}" target="_blank" rel="noopener noreferrer">查看来源原文 ↗</a>`:'<span class="article">来源待补充</span>'}</div>`).join('')}</section><section class="block"><h3><span class="number">03</span>整改措施</h3><p>${esc(r.measures)}</p></section><section class="block note"><h3>ⓘ 适用说明 / 上位法兜底</h3><p>${esc(r.note)}</p></section></div><div class="detailactions"><button class="primary" id="copy">复制完整整改条目</button>${admin?'<button id="edit">编辑条目</button><button id="del">删除</button>':'<button id="toedit">维护此条目</button>'}</div>`;$('#copy').onclick=()=>copy(r,bases);if(admin){$('#edit').onclick=()=>openEdit(r);$('#del').onclick=()=>ask('删除这个条目？','仅修改当前浏览器的隐患库。删除后可立即撤销。',()=>{lastDeleted=structuredClone(data);if(save(data.filter(x=>x.id!==r.id))){places();render();toast('已删除，可在管理区撤销');addUndo()}})}else $('#toedit').onclick=()=>{setAdmin(true);openEdit(r)}}
function textOf(r,bases){return `${r.title}\n\n隐患专业描述\n${r.description}\n\n法规原文依据\n${bases.map(b=>`${b.name} ${b.article}【${b.role}；${b.scope}】\n${b.quote||'原文待核验'}\n来源：${b.url}`).join('\n\n')}\n\n整改措施\n${r.measures}\n\n适用说明 / 上位法兜底\n${r.note}\n\n核验状态：${r.status}；核验日期：${r.checked||'未填写'}。使用前复核现行有效性。`}
async function copy(r,b){try{await navigator.clipboard.writeText(textOf(r,b));toast('已复制描述、原文依据、整改措施与适用说明')}catch{const t=document.createElement('textarea');t.value=textOf(r,b);document.body.append(t);t.select();const ok=document.execCommand('copy');t.remove();toast(ok?'已复制':'复制失败，请手动选择文本复制')}}
function setAdmin(v){admin=v;$('#admin').hidden=!v;$('#manage').classList.toggle('active',v);$('#home').classList.toggle('active',!v);render()}
function addUndo(){if($('#undo'))return;const b=document.createElement('button');b.id='undo';b.textContent='撤销删除';b.onclick=()=>{if(lastDeleted&&save(lastDeleted)){lastDeleted=null;b.remove();places();render();toast('已恢复')}};$('#admin .actions').append(b)}
function ask(title,msg,fn){$('#confirmTitle').textContent=title;$('#confirmText').textContent=msg;$('#confirm').showModal();$('#yes').onclick=()=>{$('#confirm').close();fn()};$('#no').onclick=()=>$('#confirm').close()}
const fields=['name','article','level','scope','role','url','quote'];
function lawfield(b={name:'',article:'',quote:'',url:'',level:'法律',scope:'全国',role:'待核验'}){const el=document.createElement('div');el.className='lawform';el.innerHTML=`<div class="formgrid"><label>法规 / 标准名称<input data-k="name" required value="${esc(b.name)}"></label><label>条、款、项 / 节选范围<input data-k="article" required value="${esc(b.article)}"></label><label>法规类别<select data-k="level">${['法律','行政法规','强制性国家标准','推荐性标准','部门规章','地方性法规','地方政府规章'].map(x=>`<option ${b.level===x?'selected':''}>${x}</option>`).join('')}</select></label><label>地区<select data-k="scope">${['全国','江苏／南京','南京'].map(x=>`<option ${b.scope===x?'selected':''}>${x}</option>`).join('')}</select></label><label>依据角色<input data-k="role" required value="${esc(b.role)}"></label><label>来源链接<input type="url" data-k="url" value="${esc(b.url)}" placeholder="https://…"></label></div><label>原文（不得用概括冒充原文）<textarea data-k="quote" rows="4">${esc(b.quote)}</textarea></label><button type="button" class="remove">移除此依据</button>`;el.querySelector('.remove').onclick=()=>{if($$('.lawform').length<2)return toast('每个条目至少保留一条依据');el.remove()};$('#lawfields').append(el)}
function openEdit(r){editing=r?.id||null;$('#editform').reset();$('#editTitle').textContent=r?'编辑隐患':'新增隐患';$('#lawfields').innerHTML='';for(const k of ['title','category','keywords','description','measures','note','mode','status','checked']){const e=$('#editform').elements[k];if(r)e.value=r[k]}$('#editform').elements.places.value=r?r.places.join('，'):'';if(r)r.bases.forEach(lawfield);else lawfield();$('#editor').showModal()}
$('#editform').onsubmit=e=>{e.preventDefault();const f=e.target,r={id:editing||'U'+Date.now(),bases:[]};for(const k of ['title','category','keywords','description','measures','note','mode','status','checked'])r[k]=f.elements[k].value.trim();r.places=f.elements.places.value.split(/[,，]/).map(s=>s.trim()).filter(Boolean);r.bases=$$('.lawform').map(el=>Object.fromEntries(fields.map(k=>[k,el.querySelector(`[data-k="${k}"]`).value.trim()])));const next=data.map(x=>x.id===editing?r:x);if(!editing)next.push(r);if(save(next)){$('#editor').close();$('#search').value='';$('#place').value='';$('#level').value='';$('#region').value='';selected=r.id;places();render();toast('已保存到当前浏览器，建议导出备份')}};
$('#addlaw').onclick=()=>lawfield();$('#add').onclick=()=>openEdit();$('#close').onclick=$('#cancel').onclick=()=>$('#editor').close();$('#manage').onclick=()=>setAdmin(true);$('#home').onclick=()=>setAdmin(false);$('#search').oninput=render;['place','level','region'].forEach(x=>$('#'+x).onchange=render);$('#clear').onclick=()=>{$('#search').value='';render();$('#search').focus()};$('#reset').onclick=()=>{['search','place','level','region'].forEach(x=>$('#'+x).value='');render()};document.addEventListener('keydown',e=>{if(e.key==='/'&&!['INPUT','TEXTAREA','SELECT'].includes(document.activeElement.tagName)&&!$('dialog[open]')){e.preventDefault();$('#search').focus()}});
$('#export').onclick=()=>{const a=document.createElement('a'),blob=new Blob([JSON.stringify({schemaVersion:1,exportedAt:new Date().toISOString(),records:data},null,2)],{type:'application/json'});a.href=URL.createObjectURL(blob);a.download='安全隐患库_'+new Date().toISOString().slice(0,10)+'_ChatGPT.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),2000);toast('备份已导出，包含当前全部条目')};$('#import').onclick=()=>$('#file').click();$('#file').onchange=async e=>{const file=e.target.files[0];if(!file)return;try{if(file.size>10*1024*1024)throw Error('文件超过10MB');const obj=JSON.parse(await file.text());if(!Array.isArray(obj)&&obj.schemaVersion!==1)throw Error('不支持的备份版本');const incoming=validate(Array.isArray(obj)?obj:obj.records),oldIds=new Set(data.map(x=>x.id)),overlap=incoming.filter(x=>oldIds.has(x.id)).length;ask('导入隐患库',`共 ${incoming.length} 条，其中 ${overlap} 条同ID记录将更新，其余新增。现有其他条目保留。请确认导入来源可信。`,()=>{const m=new Map(data.map(x=>[x.id,x]));incoming.forEach(x=>m.set(x.id,x));if(save([...m.values()])){places();render();toast('导入成功，已保存到当前浏览器')}})}catch(err){toast('导入失败：'+err.message)}e.target.value=''};
places();render();

